apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextproject-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextproject-main
  template:
    metadata:
      labels:
        app: nextproject-main
    spec:
      containers:
        - name: main-service
          image: nextproject-main:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: nextproject-config
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: nextproject-secrets
                  key: SECRET_KEY
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 15
